#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Soshi Saiki 　　　　　
# SPDX-License-Identifier: GPL-3.0
import sys


#x = 0.0
#for n in sys.argv[1:]:
    #x += float(n)

#print(x)

nums = [ float(e) for e in sys.argv[1:] ]
print(sum(nums))
print(nums)

