#!/usr/bin/python3
# PSDX-FileCopyrightText: 2023 Soshi Saiki
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

    print(ans)

