#!/usr/bin/python3
# PSDX-FileCopyrightText: 2023 Soshi Saiki
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
amari = 0
for line in sys.stdin:
    line = line.strip()
    try:
        ans += int(line)
    except ValueError:
        try :
            ans += float(line)
        except ValueError:
            print("the line {line}")

    
#print(ans)
      
amari = ans%2 #余り

if amari == 1:
    print(ans, "奇数です")
elif amari == 0:
    print(ans, "偶数です")
else:
    print(ans, "偶数でも奇数でもない")
